### PR TITLE
STUD-2265 - JWT Claims Fix

### PR DESCRIPTION
**Pull request by austinarbor-wk**
# Description
Generate a signed claims struct instead of a string as authorization to reaper

# Regression Test
Deployed File Utils with updated cobra package: https://app-staging.onecloud.io/onecloud-qa/self-service/workspace/148/168/chains/13631/history/857860/1537668

### CODE REVIEW

**Comment by aviary-wf** [comment]
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

**Review by danerubado-wk — APPROVED** [review]
LGTM! just wondering what issue we saw that led to this fix?

**Comment by ryancurtin-wk** [comment]
@danerubado-wk @austinarbor-wk - Austin did some work in the reaper to support our current strategy that isn't exactly compliant with the JWT spec.  He already built forward-compatibility into the reaper, so this was really just a QOL improvement for future devs (we'd have to rebuild all bizapps before removing that code in the reaper though).

**Review by ryancurtin-wk — APPROVED** [review]

**Comment by austinarbor-wk** [comment]
@danerubado-wk here we _were_ just signing a pure string, not a map of claims, which isn't entirely up to spec. When we upgraded elixir from 1.11 to 1.14, the new jwt library we started using (our old library didn't work with 1.14 anymore and was no longer maintained) would not properly verify these claims since they didn't deserialize into a proper map. i had to [backport some auth logic](https://github.com/Workiva/oc-reaper/blob/master/lib/reaper/authorization.ex#L63) to support this verification mechanism. there are rumblings that the cerebral repo might be getting split out sooner rather than later so i wanted to get this in now before that happens. once all the bizapps are republished i can remove the backported logic in reaper

**Comment by austinarbor-wk** [comment]
QA +1

**Comment by austinarbor-wk** [comment]
@Workiva/release-management-p

**Review by rmconsole-wf — APPROVED** [review]
+1 from RM

**Pull request merged**
